### ISSUE TITLE
What is the correct package version? | Qual e a versão do pacote?

### ISSUE THREAD

**Issue by rogepage** [vluzrmos/collective-html#1]
[InvalidArgumentException]
Could not find package vluzmos/collective-html at any version for your mini
mum-stability (stable). Check the package spelling or your minimum-stability

**Comment by vluzrmos** [comment]
Run the command: `composer require vluzrmos/collective-html`

the current version is 1.0.4

If you want to install the wildcard:

`composer require "vluzrmos/collective-html=1.0.*"`

or just add it on your `composer.json`:

"vluzrmos/collective-html":"1.0.*"

**Comment by vluzrmos** [comment]
I found that bug too, and i'll fix that in a minute.

**Comment by vluzrmos** [comment]
Fixed that on version 1.0.5. 
Thanks @rogepage e @henriquesousa
