### ISSUE TITLE
Select placeholdem

### ISSUE THREAD

**Issue by nigareps** [vluzrmos/collective-html#4]
Select list doesn't have placeholder option.

**Comment by vluzrmos** [comment]
That is an html limitation, it is not an issue of this package. 
You could do something like this to solve that:

``` php
Form::select("name", ['' => "Select a name'] + $arrayOfOptions,....) 
```

**Comment by nigareps** [comment]
But in this package there is placeholder option https://github.com/LaravelCollective/html/blob/5.1/src/FormBuilder.php#L502

**Comment by vluzrmos** [comment]
That option does exactly what I said, but I will improve the package with that.

**Comment by vluzrmos** [comment]
Done, please update to version 1.0.10.
